### ISSUE TITLE
Not compatible with v1.0.0 of finput

### ISSUE THREAD

**Issue by EamonnHarrison** [sh1989/finput-react#3]
After upgrading to v1.0.0 of finput, I get `Uncaught (in promise) TypeError: this.input.setRawValue is not a function` on line 30 (`this.input.setRawValue(value);`)

**Comment by EamonnHarrison** [comment]
Turns out finput inadvertently released a 1.5.3 version (which is bugged) so using ^1.0.0 in my package.json file had downloaded that version. Forcing strict use of 1.0.0 fixed the issue.
